# Tên ứng dụng của bạn
spring.application.name=daugiaonline

server.port=${PORT:8080}
# 1. KẾT NỐI DATABASE (TiDB Serverless - MySQL)
# URL này bạn lấy từ nút Connect trên TiDB (nhớ giữ nguyên các tham số sslMode phía sau)
spring.datasource.url=jdbc:mysql://gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/auction_db?sslMode=VERIFY_IDENTITY&enabledTLSProtocols=TLSv1.2,TLSv1.3
spring.datasource.username=49Za4QYEm2QKpKB.root
spring.datasource.password=c3q4YjNPvhm4S59p
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Cấu hình Hibernate tự động sinh bảng
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# 2. KẾT NỐI CACHE & REAL-TIME (Upstash Redis)
# Lấy thông số này bên tab Spring Boot của Upstash
spring.data.redis.host=unbiased-yeti-99669.upstash.io
spring.data.redis.port=6379
spring.data.redis.password=gQAAAAAAAYVVAAIgcDIyOTA5N2Q5YTg4NWE0YWNiODk4MTI1Y2E3NmE4OGY4ZA
spring.data.redis.ssl.enabled=true


# Cloudinary Configuration
cloudinary.cloud-name=dmh7q4fkt
cloudinary.api-key=381387661578335
cloudinary.api-secret=eHh-U62ZWeRzJ4e71zF7oRk_YF0

# VNPay Configuration
vnpay.tmn-code=9ZW7NJBG
vnpay.hash-secret=XXT6Z5418273QCOQFFSBKF28LG8Y3W9O
vnpay.url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.return-url=http://localhost:8080/api/v1/payment/vnpay-return

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=vuvipkoko08@gmail.com
spring.mail.password=iuoz gpkb isul hawf
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true